export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Sweden',
  'Switzerland',
  'Norway',
  'Denmark',
  'Finland',
  'Japan',
  'China',
  'India',
  'Brazil',
  'Mexico',
  'South Africa',
  'Russia',
  'Ukraine',
  'Belarus',
  'Poland',
  'Turkey',
  'South Korea',
] as const;

export type Country = (typeof COUNTRIES)[number];
